name: ci
on: push
# Prevent writing to the repository using the CI token.
# Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions: read-all
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-go
        if: success()
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.18.0-rc1
      - name: cache
        if: success()
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/connect/${{ runner.os }}/x86_64/bin
            ~/.cache/connect/${{ runner.os }}/x86_64/go/pkg/mod
            ~/.cache/connect/${{ runner.os }}/x86_64/include
            ~/.cache/connect/${{ runner.os }}/x86_64/versions
          key: ${{ runner.os }}-connect-ci-${{ hashFiles('**/go.sum', 'make/**') }}
          restore-keys: |
            ${{ runner.os }}-connect-ci-
      - name: make-ci
        if: success()
        run: make ci
