name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 22 * * *'
# Prevent writing to the repository using the CI token.
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions: read-all
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.0-beta2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          stable: '!contains(${{ matrix.go }}, "beta") && !contains(${{ matrix.go }}, "rc")'
          go-version: ${{ matrix.go-version }}
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          lfs: true
      - name: Test
        run: make test
      - name: Lint
        if: matrix.go-version == '1.18.0-beta2'
        run: make lint
